import {prompt} from '../types/promptType';
import dotenv from "dotenv";
dotenv.config();

const huggingFaceApiKey = process.env.HUGGINFACE_API_KEY || null;
const modelApi = process.env.MODEL_API_URL || '';

class IaModelService{
        
    /**
     * 
     * @param query the prompt to send to the model
     * @returns the url of the auidio file generated by the model and stored in firebase
     */
    public async queryIaModel(query: prompt): Promise<string>{
        if(!huggingFaceApiKey && !modelApi){
            throw new Error('Hugging face api key or model api not found');
        }

        return 'IaModelService.queryIaModel';
    }

   
}

export default new IaModelService();