const huggingFaceApiKey = process.env.HUGGING_FACE_API_KEY || null;
class IaModelService{
    
    /**
     * 
     * @param query the prompt to send to the model
     * @returns the url of the auidio file generated by the model and stored in firebase
     */
    public async queryIaModel(query: string): Promise<string>{
        if(!huggingFaceApiKey){
            throw new Error('Hugging Face API key is missing');
        }


        return 'IaModelService.queryIaModel';
    }
}

export default new IaModelService();